window.libraryDocuments = [];
window.libraryActiveType = 'all';
window.libraryViewMode = localStorage.getItem('libraryViewMode') || 'grid';

function escapeLibraryHtml(value) { return String(value ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;'); }
function parseLibrarySize(size) { const m=String(size||'').match(/^([\d.]+)\s*(B|KB|MB|GB)$/i); return m ? Number(m[1])*({B:1,KB:1024,MB:1048576,GB:1073741824}[m[2].toUpperCase()]) : 0; }
function formatLibraryBytes(bytes) { if(!bytes)return '0 B'; const u=['B','KB','MB','GB']; const i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),3); return `${(bytes/1024**i).toFixed(i>1?1:0)} ${u[i]}`; }
function getLibraryFileIcon(type) { return ({PDF:'fa-file-pdf',DOCX:'fa-file-word',XLSX:'fa-file-excel',XLS:'fa-file-excel',CSV:'fa-file-csv',SQL:'fa-database',TXT:'fa-file-lines',MD:'fa-file-code'})[String(type).toUpperCase()]||'fa-file'; }
function getLibraryRagState(document) { const status=String(document?.status||'').toLowerCase(); if(status.includes('đã lập chỉ mục'))return{level:'ready',icon:'fa-circle-check',label:'Hybrid sẵn sàng'}; if(status.includes('qdrant')||status.includes('tái lập chỉ mục'))return{level:'degraded',icon:'fa-triangle-exclamation',label:Number(document?.chunksCount||0)>0?'Chỉ BM25':'Lỗi lập chỉ mục'}; if(status.includes('lỗi'))return{level:'error',icon:'fa-circle-xmark',label:'Lỗi xử lý'}; return{level:'processing',icon:'fa-clock',label:document?.status||'Đang xử lý'}; }

async function fetchLibraryDocuments() { try { const r=await fetch('/api/library'); const d=await r.json(); if(!r.ok)throw new Error(d.message); window.libraryDocuments=Array.isArray(d)?d:[]; renderLibraryDocuments(); } catch(e) { document.getElementById('library-docs-grid').innerHTML=`<div class="library-empty error">${escapeLibraryHtml(e.message)}</div>`; } }
function getFilteredLibraryDocuments() { const q=(document.getElementById('lib-search-input')?.value||'').toLowerCase(); let rows=window.libraryDocuments.filter(x=>(window.libraryActiveType==='all'||String(x.fileType).toUpperCase()===window.libraryActiveType)&&`${x.title} ${x.category}`.toLowerCase().includes(q)); const sort=document.getElementById('library-sort')?.value; if(sort==='name')rows.sort((a,b)=>a.title.localeCompare(b.title,'vi')); else if(sort==='size')rows.sort((a,b)=>(b.sizeBytes||parseLibrarySize(b.size))-(a.sizeBytes||parseLibrarySize(a.size))); else rows.sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))); return rows; }
function renderLibraryDocuments() { const root=document.getElementById('library-docs-grid'); if(!root)return; root.className=`library-docs-grid ${window.libraryViewMode}`; const rows=getFilteredLibraryDocuments(); const state=window.paginationState?.library||{currentPage:1,itemsPerPage:8}; const page=rows.slice((state.currentPage-1)*state.itemsPerPage,state.currentPage*state.itemsPerPage); root.innerHTML=page.length?page.map(x=>{const t=String(x.fileType||'FILE').toUpperCase();const rag=getLibraryRagState(x);return `<article class="library-doc-card" onclick="previewLibraryDocument('${escapeLibraryHtml(x.id)}')"><div class="library-card-preview type-${t.toLowerCase()}"><i class="fa-solid ${getLibraryFileIcon(t)}"></i><p>${escapeLibraryHtml(x.preview||'Bấm để xem nội dung đã trích xuất')}</p></div><div class="library-card-body"><div class="library-card-title"><i class="fa-solid ${getLibraryFileIcon(t)}"></i><strong title="${escapeLibraryHtml(x.title)}">${escapeLibraryHtml(x.title)}</strong><button onclick="event.stopPropagation();deleteLibraryDocument('${escapeLibraryHtml(x.id)}')"><i class="fa-solid fa-trash"></i></button></div><div class="library-card-meta"><span>${escapeLibraryHtml(t)} · ${escapeLibraryHtml(x.size||'-')}</span><span class="rag-${rag.level}" title="${escapeLibraryHtml(x.status||'')}"><i class="fa-solid ${rag.icon}"></i> ${escapeLibraryHtml(rag.label)}</span></div><div class="library-card-footer"><span>${Number(x.chunksCount||0)} chunks</span><span>${escapeLibraryHtml(new Date(x.updatedAt).toLocaleDateString('vi-VN'))}</span></div>${x.error?`<div class="library-card-error" title="${escapeLibraryHtml(x.error)}">${escapeLibraryHtml(x.error)}</div>`:''}</div></article>`}).join(''):'<div class="library-empty"><i class="fa-regular fa-folder-open"></i><strong>Chưa có tài liệu</strong><span>Hãy tải file lên để xây dựng kho tri thức.</span></div>'; updateLibraryStats(); document.getElementById('lib-docs-counter').textContent=`${rows.length} tài liệu`; if(typeof renderPaginationControls==='function')renderPaginationControls('library-pagination','library',rows.length,renderLibraryDocuments); }
function updateLibraryStats(){const d=window.libraryDocuments;const states=d.map(getLibraryRagState);document.getElementById('lib-stat-docs').textContent=d.length;document.getElementById('lib-stat-chunks').textContent=d.reduce((s,x)=>s+Number(x.chunksCount||0),0).toLocaleString('vi-VN');document.getElementById('lib-stat-size').textContent=formatLibraryBytes(d.reduce((s,x)=>s+Number(x.sizeBytes||parseLibrarySize(x.size)),0));document.getElementById('lib-stat-status').textContent=states.some(x=>x.level==='error')?'Có tài liệu lỗi':states.some(x=>x.level==='degraded')?'Một số tài liệu chỉ BM25':'Hybrid RAG sẵn sàng';}
function filterLibraryDocs(){if(window.paginationState?.library)window.paginationState.library.currentPage=1;renderLibraryDocuments();}
function filterLibraryCategory(type,button){window.libraryActiveType=type==='all'?'all':type;document.querySelectorAll('.library-tabs > button').forEach(x=>x.classList.remove('active'));button?.classList.add('active');filterLibraryDocs();}
function toggleLibraryView(){window.libraryViewMode=window.libraryViewMode==='grid'?'list':'grid';localStorage.setItem('libraryViewMode',window.libraryViewMode);document.getElementById('library-view-icon').className=`fa-solid ${window.libraryViewMode==='grid'?'fa-list':'fa-grip'}`;renderLibraryDocuments();}
function openUploadLibraryModal(){document.getElementById('library-upload-form')?.reset();document.getElementById('library-drop-zone')?.classList.remove('has-file');openModal('library-upload-modal');}
function closeLibraryModal(){closeModal('library-upload-modal');}
function handleLibraryModalBackdrop(e){if(e.target.id==='library-upload-modal')closeLibraryModal();}
function handleLibraryFileSelection(e){const f=e.target.files?.[0];if(!f)return;const ext=f.name.split('.').pop().toUpperCase();const supported=['PDF','DOCX','XLSX','XLS','CSV','SQL','TXT','MD'];if(!supported.includes(ext)){e.target.value='';return showToast('Định dạng file chưa được hỗ trợ.','warn');}document.getElementById('library-title-input').value=f.name;document.getElementById('library-type-input').value=ext;document.getElementById('library-size-input').value=formatLibraryBytes(f.size);document.getElementById('library-drop-zone').classList.add('has-file');}
function fileToBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});}
async function submitLibraryDocument(e){e.preventDefault();const file=document.getElementById('library-file-input').files?.[0];if(!file)return showToast('Hãy chọn file.','warn');const button=document.getElementById('library-submit-btn');button.disabled=true;button.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Đang đọc & lập chỉ mục...';try{const payload={title:document.getElementById('library-title-input').value.trim(),fileType:document.getElementById('library-type-input').value,size:document.getElementById('library-size-input').value,category:document.getElementById('library-category-input').value,contentBase64:await fileToBase64(file)};const r=await fetch('/api/library/add',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message);window.libraryDocuments=d.documents;closeLibraryModal();renderLibraryDocuments();if(d.status==='duplicate')showToast(d.message||'Tệp đã tồn tại trong Thư viện.','info');else{const rag=getLibraryRagState(d.document);if(rag.level==='ready')showToast('Đã đọc và lập chỉ mục Hybrid RAG.','success');else showToast(`Đã lưu tài liệu nhưng ${rag.label.toLowerCase()}: ${d.document?.error||d.document?.status||''}`,'warn');}}catch(err){showToast(err.message,'error','Không thể tải tài liệu');}finally{button.disabled=false;button.innerHTML='<i class="fa-solid fa-wand-magic-sparkles"></i> Tải lên & xử lý';}}
async function previewLibraryDocument(id){openModal('library-preview-modal');const item=window.libraryDocuments.find(x=>x.id===id);document.getElementById('library-preview-title').textContent=item?.title||'Xem tài liệu';document.getElementById('library-preview-meta').textContent=`${item?.fileType||''} · ${item?.chunksCount||0} chunks · ${item?.status||''}`;document.getElementById('library-open-original').href=`/api/library/${encodeURIComponent(id)}/file`;const content=document.getElementById('library-preview-content');content.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Đang tải nội dung...';try{const r=await fetch(`/api/library/${encodeURIComponent(id)}/content`);const d=await r.json();if(!r.ok)throw new Error(d.message);content.innerHTML=d.content?`<pre>${escapeLibraryHtml(d.content)}</pre>`:`<div class="library-empty">Chưa trích xuất được nội dung.</div>`;}catch(e){content.innerHTML=`<div class="library-empty error">${escapeLibraryHtml(e.message)}</div>`;}}
function closeLibraryPreview(){closeModal('library-preview-modal');}function handleLibraryPreviewBackdrop(e){if(e.target.id==='library-preview-modal')closeLibraryPreview();}
async function deleteLibraryDocument(id){const item=window.libraryDocuments.find(x=>x.id===id);if(!item||!confirm(`Xóa tài liệu "${item.title}"?`))return;const r=await fetch('/api/library/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!r.ok)return showToast(d.message,'error');window.libraryDocuments=d.documents;renderLibraryDocuments();showToast('Đã xóa tài liệu và vector liên quan.','info');}
Object.assign(window,{fetchLibraryDocuments,renderLibraryDocuments,filterLibraryDocs,filterLibraryCategory,toggleLibraryView,openUploadLibraryModal,closeLibraryModal,handleLibraryModalBackdrop,handleLibraryFileSelection,submitLibraryDocument,previewLibraryDocument,closeLibraryPreview,handleLibraryPreviewBackdrop,deleteLibraryDocument});
