'use strict';
const test = require('node:test');
process.env.WORKFLOW_PLUGINS_ENABLED = 'true';
const assert = require('node:assert/strict');
const http = require('node:http');
const os = require('node:os');
const path = require('node:path');

test('browser manages plugin publication and completes a run through the slot form', { skip: process.env.KNOWLEDGEHUB_TEST_BROWSER !== '1' }, async t => {
  process.env.BOOTSTRAP_ADMIN_PASSWORD = 'isolated-browser-test-only';
  const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || path.join(os.tmpdir(), 'knowledgehub-phase1-ui-tools/node_modules/playwright'));
  const auth = require('../src/backend/services/auth_service');
  const providers = require('../src/backend/services/ai_provider_manager');
  t.mock.method(providers, 'getProviderForExecution', () => ({ status: 'unconfigured' }));
  t.mock.method(auth, 'getAccountBySession', () => ({ id: 'admin', username: 'admin', displayName: 'Test admin', role: 'admin' }));
  // UI history normally requires PostgreSQL. Isolate that store for this browser
  // test; plugin/run persistence below uses the real JSON domain repository.
  const history = require('../src/backend/services/page_chat_history_service'), sessions = new Map();
  t.mock.method(history, 'list', async () => [...sessions.values()].map(item => structuredClone(item)));
  t.mock.method(history, 'save', async (_, { changes = [], deleted = [] }) => {
    const versions = {};
    for (const item of deleted) sessions.delete(item.id);
    for (const item of changes) { versions[item.id] = item.version + 1; sessions.set(item.id, { ...structuredClone(item), version: versions[item.id] }); }
    return { versions };
  });
  const { handleRequest } = require('../src/backend/routes/router');
  const automation = require('../src/backend/automation');
  const server = http.createServer((req, res) => handleRequest(req, res).catch(error => { res.writeHead(500); res.end(error.message); }));
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => { server.closeAllConnections(); return new Promise(resolve => server.close(resolve)); });
  const browser = await chromium.launch({ executablePath: process.env.TEST_BROWSER_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
  t.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(5000);
  const failures = []; page.on('pageerror', error => failures.push(error.message));
  await automation.configure({ enabled: false, revision: null }, { accountId: 'admin', permissions: ['admin'] });
  await page.goto(`http://127.0.0.1:${server.address().port}/workflows`, { waitUntil: 'domcontentloaded' });
  assert.equal(await page.getByRole('heading', { name: 'Workflow Automation', exact: true }).count(), 0);
  await page.getByText('Chưa có mẫu đang thiết kế', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Nạp 5 mẫu', exact: true }).count(), 0);
  assert.equal(await page.getByRole('button', { name: 'Tắt nhận tác vụ mới', exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Tạo mẫu', exact: true }).waitFor();
  const starter = require('../src/backend/automation/pilot.json');
  for (const template of starter.templates) await automation.registry.import({ manifest: { ...starter.manifest, id: `phase1_example_${template.id}`, name: template.name }, templates: [{ ...structuredClone(template), enabled: true, instructions: template.instructions || '' }] }, { accountId: 'admin', permissions: ['admin'] });
  await page.getByRole('button', { name: 'Làm mới', exact: true }).click();
  // Edit a real definition through forms; hidden advanced JSON is optional.
  await page.locator('#wp-packages article').nth(4).waitFor();
  assert.equal(await page.locator('#wp-packages article').count(), 5);
  const lookupActions = page.locator('#wp-packages article[data-template-id="lookup"] .workflow-card-actions');
  assert.equal(await lookupActions.locator(':scope > button').count(), 3);
  await lookupActions.getByRole('button', { name: 'Thêm thao tác', exact: true }).click();
  await lookupActions.getByRole('button', { name: 'Validate', exact: true }).waitFor();
  await lookupActions.getByRole('button', { name: 'Thêm thao tác', exact: true }).press('Escape');
  assert.equal(await lookupActions.getByRole('button', { name: 'Validate', exact: true }).isVisible(), false);
  assert.equal((await automation.repository.list('catalog')).filter(item => item.id.startsWith('phase1_example_')).every(item => item.draft.templates.length === 1), true);
  await page.locator('#wp-packages article[data-template-id="range"]').getByRole('button', { name: 'Sửa template', exact: true }).click();
  const phaseButtons = page.locator('.wp-node-select');
  assert.ok(await phaseButtons.count() > 1);
  assert.equal(await phaseButtons.nth(0).isVisible(),false);
  assert.deepEqual(await page.getByRole('tab').allTextContents(),['Nhận diện & đầu vào','Nguồn dữ liệu','Kịch bản các bước','Kết quả','Chạy thử']);
  await page.getByRole('tab',{name:'Kịch bản các bước',exact:true}).click();
  await phaseButtons.nth(1).click();
  assert.equal(await page.locator('.wp-step-inspector > fieldset:visible').count(), 1);
  assert.equal(await phaseButtons.nth(1).getAttribute('aria-pressed'), 'true');
  await page.screenshot({ path: path.join(os.tmpdir(), 'knowledgehub-node-builder.png'), fullPage: true });
  await page.getByRole('button', { name: 'Đóng', exact: true }).click();
  const beforeEdit = (await automation.repository.list('catalog')).find(item => item.id === 'phase1_example_lookup').draft;
  await page.locator('#wp-packages article[data-template-id="lookup"]').getByRole('button', { name: 'Sửa template', exact: true }).click();
  await page.getByRole('tab', { name: 'Nhận diện & đầu vào', exact: true }).click();
  await page.locator('.wp-slot-card').getByLabel('Tên hiển thị', { exact: true }).fill('Mã cần tra cứu');
  await page.getByLabel('Câu hỏi khi thiếu thông tin', { exact: true }).fill('Bạn muốn tra cứu mã nào?');
  assert.equal(await page.getByRole('tabpanel').count(), 1);
  await page.getByRole('tab', { name: 'Nhận diện & đầu vào', exact: true }).focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.getByRole('tab', { name: 'Nguồn dữ liệu', exact: true }).getAttribute('aria-selected'), 'true');
  await page.getByRole('button', { name: 'Thêm nguồn truy vấn', exact: true }).click();
  assert.equal(await page.locator('.wp-type-options > button').count(), 4);
  await page.getByRole('button', { name: /Truy vấn SQL Tạo sẵn/ }).click();
  assert.equal(await page.locator('.wp-bindings-section .wp-sql-editor').count(), 1);
  assert.equal(await page.locator('.wp-bindings-section .wp-sql-editor').inputValue(), '');
  await page.locator('.wp-bindings-section .wp-sql-editor').fill("SELECT '<img src=x onerror=alert(1)>' AS [Name]\nFROM [dbo].[Records] WHERE [ID] = @id");
  assert.equal(await page.locator('.wp-code-highlight .wp-code-keyword').first().innerText(),'SELECT');
  assert.equal(await page.locator('.wp-code-highlight img').count(),0);
  assert.equal(await page.locator('.wp-code-editor[data-language="sql"] .wp-code-line').count(),2);
  assert.equal(await page.locator('.wp-query-advanced').getAttribute('open'), null);
  await page.getByRole('button', { name: 'Xóa trường query_1', exact: true }).click();
  await page.getByRole('button', { name: 'Thêm nguồn truy vấn', exact: true }).click();
  await page.getByRole('button', { name: /^API HTTP/ }).click();
  const sourceHeader = await page.locator('.wp-source-card .wp-field-heading').last().evaluate(header => {
    const label=header.getBoundingClientRect(), badge=header.querySelector('.wp-field-type').getBoundingClientRect(), remove=header.querySelector('button').getBoundingClientRect();
    return { labelCenter:label.y+label.height/2, badgeCenter:badge.y+badge.height/2, removeCenter:remove.y+remove.height/2 };
  });
  assert.ok(Math.abs(sourceHeader.labelCenter-sourceHeader.badgeCenter)<2);
  assert.ok(Math.abs(sourceHeader.labelCenter-sourceHeader.removeCenter)<2);
  await page.getByLabel('Địa chỉ API HTTP/HTTPS', { exact: true }).fill('https://example.com/records');
  await page.getByLabel('Phương thức', {exact:true}).selectOption('POST');
  await page.getByLabel('Dữ liệu gửi (body)', {exact:true}).selectOption('json');
  await page.locator('.wp-source-form .wp-advanced').filter({hasText:'Nâng cao: chỉnh JSON'}).last().locator(':scope > summary').click();
  const jsonCode=page.locator('.wp-source-form .wp-code-editor[data-language="json"]').last();
  await jsonCode.locator('textarea').fill('{"message":"<script>example</script>","count":2}');
  await jsonCode.getByRole('button',{name:'Định dạng JSON',exact:true}).click();
  assert.equal(await jsonCode.locator('textarea').inputValue(),'{\n  "message": "<script>example</script>",\n  "count": 2\n}');
  assert.equal(await jsonCode.locator('.wp-code-highlight script').count(),0);
  await page.getByLabel('Lấy dữ liệu cho Lấy toàn bộ body từ bước trước (tùy chọn)', {exact:true}).selectOption('{{steps.lookup}}');
  assert.equal(await page.getByLabel('Lấy toàn bộ body từ bước trước (tùy chọn)', {exact:true}).inputValue(),'{{steps.lookup}}');
  await page.getByLabel('Xác thực', {exact:true}).selectOption('bearer');
  await page.getByLabel('Biến môi trường chứa token', {exact:true}).fill('WORKFLOW_TEST_TOKEN');
  assert.equal(await page.getByLabel('Đường dẫn dữ liệu trong JSON (để trống lấy toàn bộ)', { exact: true }).count(), 1);
  await page.getByRole('tab',{name:'Kịch bản các bước',exact:true}).click();
  await page.getByRole('combobox', { name:'Thao tác của bước',exact:true }).selectOption('sql');
  await page.getByLabel('Nguồn dữ liệu sử dụng', {exact:true}).selectOption('query_1');
  assert.equal(await page.getByLabel('Nguồn dữ liệu sử dụng', {exact:true}).inputValue(),'query_1');
  assert.equal(await page.getByRole('combobox', { name:'Thao tác của bước',exact:true }).inputValue(),'source');
  await page.getByRole('combobox', { name:'Thao tác của bước',exact:true }).selectOption('transform');
  await page.getByRole('tab',{name:'Nguồn dữ liệu',exact:true}).click();
  await page.getByRole('button', { name: 'Xóa trường query_1', exact: true }).click();
  await page.getByRole('button', { name: 'Thêm nguồn truy vấn', exact: true }).click();
  await page.getByRole('button', { name: /^Kết quả bước trước Dùng lại/ }).click();
  const referencePicker=page.getByRole('combobox', { name:'Lấy dữ liệu cho Dữ liệu cần kế thừa',exact:true });
  await referencePicker.selectOption('{{steps.lookup}}');
  assert.equal(await page.getByLabel('Dữ liệu cần kế thừa', { exact: true }).inputValue(), '{{steps.lookup}}');
  await page.getByRole('button', { name: 'Xóa trường query_1', exact: true }).click();
  await page.getByRole('tab', { name: 'Nhận diện & đầu vào', exact: true }).click();
  assert.equal(await page.getByLabel('Câu hỏi khi thiếu thông tin', { exact: true }).inputValue(), 'Bạn muốn tra cứu mã nào?');
  assert.equal(await page.locator('.wp-builder-grid').evaluate(node => {
    const inspector = node.querySelector('.wp-step-inspector').getBoundingClientRect();
    const shared = node.querySelector('.wp-shared-config').getBoundingClientRect();
    return inspector.bottom <= shared.top && node.scrollWidth <= node.clientWidth + 1;
  }), true);
  await page.getByRole('tab', { name: 'Chạy thử', exact: true }).click();
  const fixtureSection = page.locator('.wp-fixtures-section');
  assert.equal(await fixtureSection.locator('input:not([type="checkbox"]):visible').evaluateAll(inputs => inputs.every(input => input.getBoundingClientRect().width >= 100)), true);
  assert.equal(await fixtureSection.evaluate(node => node.scrollWidth <= node.clientWidth + 1), true);
  await fixtureSection.getByLabel('Tên trường hợp', { exact: true }).fill('Tra cứu mã hợp lệ');
  await fixtureSection.locator('.wp-fixture-grid > section').first().getByRole('textbox').fill('A002');
  await fixtureSection.locator('.wp-fixture-grid > section').last().getByRole('textbox').first().fill('A002');
  await page.getByRole('tab', { name: 'Kết quả', exact: true }).click();
  const previousTheme = await page.evaluate(() => document.documentElement.getAttribute('data-theme'));
  await page.evaluate(() => document.documentElement.setAttribute('data-theme', 'dark'));
  assert.equal(await page.getByRole('tabpanel').evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(24, 36, 55)');
  await page.evaluate(theme => { if (theme) document.documentElement.setAttribute('data-theme', theme); else document.documentElement.removeAttribute('data-theme'); }, previousTheme);
  await page.locator('.wp-output-column').first().getByLabel('Tên hiển thị', { exact: true }).fill('Mã kết quả');
  assert.equal(await page.locator('.wp-output-section').getByLabel('Tên trường', { exact: true }).count(), 0);
  assert.equal(await page.locator('.workflow-json-editor:visible').count(), 0);
  await page.screenshot({ path: path.join(os.tmpdir(), 'knowledgehub-template-editor.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.locator('.workflow-editor-dialog').evaluate(node => node.scrollWidth <= node.clientWidth + 1), true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Lưu draft mới', exact: true }).click();
  await page.locator('.workflow-editor-dialog').waitFor({ state: 'hidden' });
  const afterEdit = (await automation.repository.list('catalog')).find(item => item.id === 'phase1_example_lookup').draft;
  const expected = structuredClone(beforeEdit); expected.templates[0].inputs.code.label = 'Mã cần tra cứu';
  expected.templates[0].output.presentation.labels.code = 'Mã kết quả';
  expected.templates[0].fixtures[0].name = 'Tra cứu mã hợp lệ'; expected.templates[0].fixtures[0].input.code = 'A002'; expected.templates[0].fixtures[0].expected.code = 'A002';
  expected.manifest.domain = ''; expected.manifest.tags = []; expected.templates[0].bindings = {};
  assert.deepEqual(afterEdit, expected);
  await page.locator('#wp-packages article[data-template-id="lookup"]').getByRole('button', { name: 'Chạy fixture', exact: true }).click();
  await page.getByRole('button', { name: 'Đóng', exact: true }).click();
  await page.locator('#wp-packages article[data-template-id="lookup"]').getByRole('button', { name: 'Publish', exact: true }).click();
  await page.getByRole('button', { name: 'Bật workflow/plugin', exact: true }).click();
  const lookup = page.locator('#wp-packages article').filter({ has: page.getByRole('heading', { name: 'Tra cứu đối tượng', exact: true }) });
  await lookup.getByRole('button', { name: 'Thêm thao tác', exact: true }).click();
  await lookup.getByRole('button', { name: 'Thử kịch bản', exact: true }).click();
  await page.getByLabel('Bạn muốn tra cứu mã nào?').fill('UI-001');
  await page.getByRole('button', { name: 'Bổ sung và tiếp tục', exact: true }).click();
  const run = (await automation.repository.list('runs'))[0];
  await automation.runtime.process(run.id);
  await page.locator('.workflow-execution-panel').getByText('Tra cứu đối tượng · Hoàn thành', { exact: true }).waitFor();
  assert.deepEqual((await automation.repository.get('runs', run.id)).result, { code: 'UI-001', source: 'fixture' });
  assert.equal(failures.length, 0, failures.join('\n'));
  await page.screenshot({ path: path.join(os.tmpdir(), 'knowledgehub-phase1-ui.png'), fullPage: true });
  // Mobile layout and reload recover the same owner-scoped run.
  await page.getByRole('button', { name: 'Đóng', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 }); await page.reload({ waitUntil: 'domcontentloaded' });
  await page.locator('.wp-history > summary').click();
  await page.locator('#wp-runs').getByRole('button', { name: /Tra cứu đối tượng.*Hoàn thành/ }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), true);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator('#wp-packages article').filter({ has: page.getByRole('heading', { name: 'Tra cứu đối tượng', exact: true }) }).getByRole('button', { name: 'Dùng trong chat', exact: true }).click();
  assert.equal(await page.locator('#page-chat-user-input').inputValue(), 'Tra cứu đối tượng');
  await page.locator('#page-chat-user-input').fill('Tra cứu đối tượng');
  await page.locator('#page-chat-send-button').click();
  await page.getByLabel('Bạn muốn tra cứu mã nào?').fill('CHAT-001');
  await page.getByRole('button', { name: 'Bổ sung và tiếp tục', exact: true }).click();
  const chatRun = (await automation.repository.list('runs')).find(item => item.id !== run.id);
  assert.ok(chatRun); await automation.runtime.process(chatRun.id);
  await page.locator('.workflow-execution-panel').getByText('Tra cứu đối tượng · Hoàn thành', { exact: true }).waitFor();
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.locator('.workflow-execution-panel').getByText('Tra cứu đối tượng · Hoàn thành', { exact: true }).waitFor();
  assert.equal((await automation.repository.list('runs')).length, 2, 'Reload restores the existing runs without creating another run');
  await page.waitForFunction(() => window.chatSessions.some(session => session.messages.some(message => message.html?.includes('Tra cứu đối tượng · Hoàn thành'))));
  // Nested objects, lists and false booleans submit typed values without JSON.
  let submitted;
  await page.route('**/api/automation-runs/structured-ui/inputs', async route => {
    submitted = route.request().postDataJSON().inputs;
    await route.fulfill({ json: { execution: { id: 'structured-ui', name: 'Thông tin', status: 'SUCCEEDED', revision: 2, result: submitted } } });
  });
  await page.evaluate(() => {
    const host = document.createElement('div'); host.id = 'structured-ui-host'; document.body.appendChild(host);
    host.innerHTML = window.renderWorkflowExecution({ id: 'structured-ui', name: 'Thông tin', status: 'WAITING_INPUT', revision: 1, missingInputs: [
      { key: 'customer', label: 'Khách hàng', schema: { type: 'object', required: ['name'], properties: { name: { type: 'string', title: 'Tên khách hàng' }, amount: { type: 'number', title: 'Số tiền' } } } },
      { key: 'codes', label: 'Danh sách mã', schema: { type: 'array', items: { type: 'string' } } },
      { key: 'confirmed', label: 'Đã xác nhận', schema: { type: 'boolean' } }
    ] });
  });
  const structured = page.locator('#structured-ui-host');
  await structured.getByLabel('Tên khách hàng').fill('An');
  await structured.getByLabel('Số tiền').fill('12.5');
  await structured.getByLabel('Mục 1').fill('A001');
  await structured.getByLabel('Đã xác nhận').selectOption('1');
  await structured.getByRole('button', { name: 'Bổ sung và tiếp tục' }).click();
  await structured.getByText('Thông tin · Hoàn thành', { exact: true }).waitFor();
  assert.deepEqual(submitted, { customer: { name: 'An', amount: 12.5 }, codes: ['A001'], confirmed: false });
  await page.evaluate(() => {
    const host = document.createElement('div'); host.id = 'result-ui-host'; document.body.appendChild(host);
    host.innerHTML = window.renderWorkflowExecution({ name: 'Tra cứu nhân viên', status: 'RUNNING', steps: [{ name: 'Tra cứu', status: 'RUNNING' }] });
  });
  const resultHost = page.locator('#result-ui-host');
  await resultHost.getByRole('status').waitFor();
  assert.equal(await resultHost.locator('.workflow-execution-panel').getAttribute('aria-busy'), 'true');
  await page.evaluate(() => {
    document.querySelector('#result-ui-host').innerHTML = window.renderWorkflowExecution({ name: 'Tra cứu nhân viên', status: 'SUCCEEDED', steps: [{ name: 'Tra cứu', status: 'SUCCEEDED' }], result: { count: 1, empty: false, employees: [{ code: 'NV007', birthday: '2024-05-24T00:00:00.000Z' }] }, presentation: { columns: { employees: ['code', 'birthday'] }, labels: { count: 'Số nhân viên tìm thấy', employees: 'Hồ sơ nhân viên', 'employees.code': 'Mã nhân viên', 'employees.birthday': 'Ngày sinh' } } });
  });
  await resultHost.getByRole('columnheader', { name: 'Ngày sinh' }).waitFor();
  assert.equal(await resultHost.getByRole('cell', { name: '24/5/2024', exact: true }).count(), 1);
  assert.equal(await resultHost.locator('.wp-result-summary').innerText(), 'Số nhân viên tìm thấy: 1');
  assert.equal(await resultHost.locator('details').evaluate(node => node.open), false);
  assert.equal(await resultHost.locator('.workflow-execution-panel').getAttribute('aria-busy'), 'false');
  let restartRequest;
  const restartRoute = async route => {
    restartRequest = route.request().postDataJSON();
    await route.fulfill({ json: { execution: { id: 'restarted-ui', templateId: 'fixture/lookup', conversationId: 'fixture-conversation', name: 'Tra cứu mới', status: 'WAITING_INPUT', revision: 1, missingInputs: [{ key: 'query', label: 'Tên hoặc mã mới', schema: { type: 'string' } }] } } });
  };
  await page.route('**/api/automation-runs', restartRoute);
  await page.evaluate(() => {
    document.querySelector('#result-ui-host').style.cssText = 'position:fixed;left:20px;top:20px;width:700px;z-index:2000';
    document.querySelector('#result-ui-host').innerHTML = window.renderWorkflowExecution({ templateId: 'fixture/lookup', conversationId: 'fixture-conversation', name: 'Kết quả trước', status: 'SUCCEEDED', result: { code: 'OLD' } });
  });
  await resultHost.getByRole('button', { name: 'Làm lại', exact: true }).click();
  await resultHost.getByLabel('Tên hoặc mã mới').waitFor();
  assert.deepEqual(restartRequest.inputs, {});
  assert.equal(restartRequest.templateId, 'fixture/lookup');
  assert.equal(restartRequest.conversationId, 'fixture-conversation');
  assert.ok(restartRequest.requestId);
  assert.equal(await resultHost.getByText('OLD', { exact: true }).count(), 1);
  const actionButtons = resultHost.locator('.wp-execution-actions').last().getByRole('button');
  const positions = await actionButtons.evaluateAll(nodes => nodes.map(node => node.getBoundingClientRect().top));
  assert.equal(positions.length, 2); assert.ok(Math.abs(positions[0] - positions[1]) < 2, JSON.stringify(await actionButtons.evaluateAll(nodes => nodes.map(node => ({rect:node.getBoundingClientRect().toJSON(),display:getComputedStyle(node.parentNode).display, css:getComputedStyle(node).cssText})))));
  await page.unroute('**/api/automation-runs', restartRoute);
  await resultHost.evaluate(node => node.remove());
  await page.goto(`http://127.0.0.1:${server.address().port}/workflows`, { waitUntil: 'domcontentloaded' });
  await page.getByRole('button', { name: 'Tạo mẫu', exact: true }).click();
  await page.getByLabel('ID gói', { exact: true }).fill('custom_business');
  await page.getByLabel('Tên gói', { exact: true }).fill('Nghiệp vụ riêng');
  await page.getByLabel('Mã mẫu nghiệp vụ', { exact: true }).fill('custom_first');
  await page.getByLabel('Tên template', { exact: true }).fill('Mẫu tự định nghĩa');
  await page.getByLabel('Cách hỏi mẫu — mỗi dòng một câu', { exact: true }).fill('Chạy nghiệp vụ riêng');
  await page.getByRole('button', { name: 'Định nghĩa mẫu mới', exact: true }).click();
  await page.getByLabel('Mã mẫu nghiệp vụ', { exact: true }).fill('custom_second');
  await page.getByLabel('Tên template', { exact: true }).fill('Mẫu thứ hai');
  await page.getByLabel('Cách hỏi mẫu — mỗi dòng một câu', { exact: true }).fill('Chạy nghiệp vụ thứ hai');
  await page.getByRole('tab',{name:'Kịch bản các bước',exact:true}).click();
  await page.locator('.wp-step-inspector > fieldset:visible').getByRole('combobox').first().selectOption('delay');
  await page.getByLabel('Thời gian chờ (mili giây)', { exact: true }).fill('25');
  await page.getByRole('button', { name: 'Thêm bước', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Bỏ bước cuối', exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Xóa bước Bước mới', exact: true }).click();
  await page.getByRole('dialog', { name: 'Xác nhận xóa' }).getByRole('button', { name: 'Hủy', exact: true }).click();
  assert.equal(await page.locator('.wp-node-select').count(), 2);
  await page.getByRole('button', { name: 'Xóa bước Bước mới', exact: true }).click();
  await page.getByRole('dialog', { name: 'Xác nhận xóa' }).getByRole('button', { name: 'Xóa', exact: true }).click();
  assert.equal(await page.locator('.wp-node-select').count(), 1);
  await page.getByRole('button', { name: 'Thêm bước', exact: true }).click();
  assert.equal(await page.locator('.wp-script-pipeline .selected').count(), 1);
  await page.getByRole('button', { name: 'Thêm bước', exact: true }).click();
  await page.locator('.wp-node-shell').nth(1).getByRole('button', { name: 'Xóa bước Bước mới', exact: true }).click();
  await page.getByRole('dialog', { name: 'Xác nhận xóa' }).getByRole('button', { name: 'Xóa', exact: true }).click();
  assert.equal(await page.locator('.wp-node-select').count(), 2);
  await page.locator('.wp-node-select').last().click();
  await page.getByLabel('Tên bước', { exact: true }).filter({ visible: true }).fill('Bước người dùng đặt');
  await page.getByRole('button', { name: 'Lưu draft mới', exact: true }).click();
  await page.locator('.workflow-editor-dialog').waitFor({ state: 'hidden' });
  const custom = await automation.repository.get('catalog', 'custom_business');
  assert.deepEqual(custom.draft.templates.map(item => item.id), ['custom_first', 'custom_second']);
  assert.equal(custom.draft.templates[1].workflow.steps[0].config.delayMs, 25);
  assert.equal(custom.draft.templates[1].workflow.steps[1].name, 'Bước người dùng đặt');
  assert.deepEqual(custom.draft.templates[0].examples, ['Chạy nghiệp vụ riêng']);
  await page.evaluate(() => document.documentElement.setAttribute('data-theme', 'dark'));
  assert.equal(await page.locator('#wp-toolbar .wp-search-box > input').evaluate(node=>getComputedStyle(node).backgroundColor),'rgba(0, 0, 0, 0)');
  await page.locator('#wp-toolbar .wp-search-box > input').focus();
  assert.equal(await page.locator('#wp-toolbar .wp-search-box').evaluate(node=>getComputedStyle(node).backgroundColor),'rgb(17, 27, 43)');
  const customCard = page.locator('#wp-packages article[data-template-id="custom_first"]');
  await customCard.getByRole('button', { name: 'Thêm thao tác', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Tách thành các mẫu độc lập', exact: true }).count(), 0);
  assert.equal(await customCard.locator('.wp-more-items').evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(21, 32, 51)');
  await customCard.getByRole('button', { name: 'Xóa mẫu', exact: true }).click();
  await page.getByRole('dialog', { name: 'Xác nhận xóa' }).getByRole('button', { name: 'Hủy', exact: true }).click();
  assert.equal(await customCard.count(), 1);
  await customCard.getByRole('button', { name: 'Thêm thao tác', exact: true }).click();
  await customCard.getByRole('button', { name: 'Xóa mẫu', exact: true }).click();
  await page.getByRole('dialog', { name: 'Xác nhận xóa' }).getByRole('button', { name: 'Xóa', exact: true }).click();
  await customCard.waitFor({ state: 'detached' });
  assert.equal(await page.locator('#wp-packages article[data-template-id="custom_second"]').count(), 1);
  assert.ok((await automation.repository.get('catalog', 'custom_business')).deletedTemplates.custom_first);
  await page.locator('#wp-packages article[data-template-id="custom_second"]').getByRole('button', { name: 'Sửa template', exact: true }).click();
  assert.equal(await page.locator('.workflow-editor-dialog').evaluate(node => getComputedStyle(node).backgroundColor.match(/\d+/g).slice(0, 3).every(value => Number(value) < 80)), true);
  const closeColors = await page.locator('.workflow-editor-dialog > header > button').evaluate(node => ({ background: getComputedStyle(node).backgroundColor, foreground: getComputedStyle(node).color }));
  assert.equal(closeColors.background, 'rgb(37, 50, 74)');
  assert.equal(closeColors.foreground, 'rgb(203, 213, 225)');
  assert.equal(await page.locator('.workflow-editor-dialog > footer .btn-secondary-sm').first().evaluate(node => getComputedStyle(node).backgroundColor), 'rgb(37, 50, 74)');
  await page.screenshot({ path: path.join(os.tmpdir(), 'knowledgehub-workflows-dark.png'), fullPage: true });
  await page.getByRole('button', { name:'Đóng', exact:true }).click();
  const publishedCard=page.locator('#wp-packages article[data-template-id="lookup"]');
  await publishedCard.getByRole('button',{name:'Thêm thao tác',exact:true}).click();
  await publishedCard.getByRole('button',{name:'Tùy chỉnh scope',exact:true}).click();
  const scopeSection=page.locator('.workflow-editor-body > .wp-editor-section');
  assert.equal(await scopeSection.evaluate(node=>getComputedStyle(node).backgroundColor),'rgb(27, 39, 59)');
  assert.equal(await scopeSection.locator(':scope > summary').evaluate(node=>getComputedStyle(node).color),'rgb(226, 232, 240)');
  await page.getByRole('button',{name:'Đóng',exact:true}).click();
  const embed=require('../src/backend/services/embed_chat_service');
  const widgetConfig=embed.createConfig({name:'Browser workflow widget',allowedOrigins:[`http://127.0.0.1:${server.address().port}`],rateLimit:100});
  const installWidget=()=>page.evaluate(id=>new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='/embed/knowledgehub-chat.js';script.dataset.embedId=id;script.dataset.theme='dark';script.onload=resolve;script.onerror=reject;document.body.appendChild(script);}),widgetConfig.id);
  await installWidget();
  let widget=page.locator('#knowledgehub-embed-host');
  await widget.getByRole('button',{name:'Mở trợ lý AI',exact:true}).click();
  await widget.getByLabel('Câu hỏi',{exact:true}).fill('Tra cứu đối tượng');await widget.getByRole('button',{name:'Gửi',exact:true}).click();
  await widget.getByText('Bạn muốn tra cứu mã nào?',{exact:true}).waitFor();
  await widget.locator('.kh-workflow input').fill('WIDGET001');await widget.getByRole('button',{name:'Bổ sung và tiếp tục',exact:true}).click();
  await widget.getByText('Tra cứu đối tượng · Đang chờ chạy',{exact:true}).waitFor();
  const widgetRun=(await automation.repository.list('runs')).find(run=>run.ownerId.startsWith(`embed:${widgetConfig.id}:`));assert.ok(widgetRun);await automation.runtime.process(widgetRun.id);
  await widget.getByText('Tra cứu đối tượng · Hoàn thành',{exact:true}).waitFor();
  await widget.getByText('WIDGET001',{exact:true}).waitFor();
  const countBeforeReload=(await automation.repository.list('runs')).length;
  await page.reload({waitUntil:'domcontentloaded'});await installWidget();widget=page.locator('#knowledgehub-embed-host');await widget.getByRole('button',{name:'Mở trợ lý AI',exact:true}).click();
  await widget.getByText('Tra cứu đối tượng · Hoàn thành',{exact:true}).waitFor();assert.equal((await automation.repository.list('runs')).length,countBeforeReload);
  await widget.getByRole('button',{name:'Làm lại',exact:true}).click();await widget.getByText('Bạn muốn tra cứu mã nào?',{exact:true}).waitFor();
  await page.evaluate(()=>document.getElementById('knowledgehub-embed-host').destroyEmbed());
  await installWidget();widget=page.locator('#knowledgehub-embed-host');await widget.getByRole('button',{name:'Mở trợ lý AI',exact:true}).click();
  assert.equal(await widget.locator('.kh-workflow').count(),0,'A new widget starts a fresh conversation');
  assert.equal(failures.length, 0, failures.join('\n'));
});

