'use strict';
process.env.WORKFLOW_PLUGINS_ENABLED = 'false';
const test = require('node:test');
const assert = require('node:assert/strict');
const http = require('node:http');

test('phase 1 HTTP, chat SSE, ownership and event replay work together', async t => {
  process.env.BOOTSTRAP_ADMIN_PASSWORD = 'isolated-automation-test-only';
  const auth = require('../src/backend/services/auth_service');
  const providers = require('../src/backend/services/ai_provider_manager');
  const automation = require('../src/backend/automation');
  const { handleRequest } = require('../src/backend/routes/router');
  t.mock.method(auth, 'getAccountBySession', token => token ? { id: token, role: token === 'admin' ? 'admin' : 'user' } : null);
  t.mock.method(providers, 'getProviderForExecution', () => ({ status: 'unconfigured' }));
  t.mock.method(automation.runtime, 'authorizeContext', async accountId => ({ accountId, permissions: ['sql:read'] }));
  const server = http.createServer((req, res) => handleRequest(req, res).catch(error => { res.statusCode = 500; res.end(JSON.stringify({ message: error.message })); }));
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => { server.closeAllConnections(); return new Promise(resolve => server.close(resolve)); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const request = (route, method = 'GET', body, account = 'admin', headers = {}) => fetch(base + route, { method, headers: { 'Content-Type': 'application/json', ...(account ? { Cookie: `kh_session=${account}` } : {}), ...headers }, ...(body ? { body: JSON.stringify(body) } : {}) });
  assert.equal((await request('/api/workflow-plugins', 'GET', null, null)).status, 401);
  assert.equal((await request('/api/workflow-plugins', 'GET', null, 'user')).status, 403);
  let settings = await (await request('/api/workflow-plugins/settings')).json();
  assert.equal(settings.enabled, false);
  assert.equal((await request('/api/workflow-plugins/settings', 'PUT', { enabled: true }, 'user')).status, 403);
  const bundle = (await (await request('/api/workflow-plugins/starter')).json()).bundle;
  assert.equal(bundle.legacySkills.length, 2);
  assert.equal((await request('/api/workflow-plugins', 'POST', { bundle })).status, 201);
  assert.equal((await request('/api/workflow-plugins/phase1_examples/test', 'POST', {})).status, 200);
  let record = (await (await request('/api/workflow-plugins/phase1_examples')).json()).package;
  assert.equal((await request('/api/workflow-plugins/phase1_examples/publish', 'POST', { revision: record.revision })).status, 200);
  assert.equal((await request('/api/automation-runs', 'POST', { templateId: 'phase1_examples/lookup', inputs: {}, conversationId: 'disabled' }, 'user')).status, 503);
  process.env.WORKFLOW_PLUGINS_ENABLED = 'true';
  assert.equal((await request('/api/workflow-plugins/settings', 'PUT', { enabled: true, revision: settings.revision })).status, 200);
  const streamed = await request('/api/intelligent-core/chat/stream', 'POST', { question: 'Tra cứu đối tượng', sessionId: 'workflow-conversation' }, 'user');
  const body = await streamed.text(); assert.equal(streamed.status, 200, body);
  const finalLine = body.split('\n').find((line, index, lines) => line.startsWith('data: ') && lines[index - 1] === 'event: final');
  assert.ok(finalLine, body); const payload = JSON.parse(finalLine.slice(6));
  assert.equal(payload.execution.status, 'WAITING_INPUT'); assert.match(payload.reply, /mã nào/);
  const id = payload.execution.id;
  assert.equal((await request(`/api/automation-runs/${id}`, 'GET', null, 'other')).status, 404);
  assert.equal((await request(`/api/automation-runs/${id}/inputs`, 'POST', { inputs: { code: 'A001' }, revision: payload.execution.revision }, 'other')).status, 404);
  const updated = await request(`/api/automation-runs/${id}/inputs`, 'POST', { inputs: { code: 'A001' }, revision: payload.execution.revision, ownerId: 'other', permissions: ['admin'] }, 'user');
  assert.equal(updated.status, 200); await automation.runtime.process(id);
  const executed = (await (await request(`/api/automation-runs/${id}`, 'GET', null, 'user')).json()).execution;
  assert.equal(executed.status, 'SUCCEEDED'); assert.equal(executed.result.code, 'A001');
  assert.equal(executed.ownerId, undefined); assert.equal(executed.definition, undefined);
  const events = await (await request(`/api/automation-runs/${id}/events`, 'GET', null, 'user', { 'Last-Event-ID': '1' })).text();
  assert.ok(events.includes('event: execution')); assert.ok(!events.startsWith('id: 1\n'));
  const allEvents = await automation.runtime.owned(id, { accountId: 'user' });
  const replay = await (await request(`/api/automation-runs/${id}/events`, 'GET', null, 'user', { 'Last-Event-ID': String(allEvents.events.length) })).text();
  assert.equal(replay, '');
  const lists = (await (await request('/api/automation-runs', 'GET', null, 'other')).json()).runs; assert.equal(lists.length, 0);
  const summaries = (await (await request('/api/automation-runs?summary=1', 'GET', null, 'user')).json()).runs;
  assert.ok(summaries.some(run=>run.id===id && run.status==='SUCCEEDED'));
  assert.equal(summaries.some(run=>run.result!==undefined || run.inputs!==undefined),false);
  assert.equal((await (await request('/api/automation-runs?summary=1','GET',null,'other')).json()).runs.length,0);
});
