'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
test('PostgreSQL phase 1 catalog and checkpoints survive repository restart with concurrent CAS', { skip: process.env.KNOWLEDGEHUB_TEST_POSTGRES !== '1' }, async t => {
  const { loadEnvironment } = require('../src/backend/storage/postgres/config'); loadEnvironment();
  const { createPool } = require('../src/backend/storage/postgres/pool');
  const { migrate } = require('../src/backend/storage/postgres/migrate');
  const { AutomationRepository } = require('../src/backend/automation/repository');
  const { PluginRegistry } = require('../src/backend/automation/registry');
  const { AutomationRuntime } = require('../src/backend/automation/runtime');
  const database = `knowledgehub_automation_test_${crypto.randomBytes(8).toString('hex')}`;
  const adminPool = createPool({ bootstrap: true }); let pool, created = false;
  t.after(async () => { if (pool) await pool.end(); if (created) await adminPool.query(`DROP DATABASE "${database}"`); await adminPool.end(); });
  await adminPool.query(`CREATE DATABASE "${database}" TEMPLATE template0`); created = true;
  pool = createPool({ bootstrap: true, database }); await migrate(pool);
  const repository = new AutomationRepository({ pool }), registry = new PluginRegistry(repository);
  const context = { accountId: 'test', permissions: ['admin'] };
  let record = await registry.import(require('../src/backend/automation/pilot.json'), context);
  await registry.test(record.id, context); record = await repository.get('catalog', record.id); await registry.publish(record.id, context, record.revision);
  const runtime = new AutomationRuntime(repository, registry, { enabled: () => true, authorizeContext: async () => context });
  const run = await runtime.create('phase1_examples/lookup', {}, context, { conversationId: 'persistent' });
  const updates = await Promise.allSettled([runtime.inputs(run.id, { code: 'A' }, context, run.revision), runtime.inputs(run.id, { code: 'B' }, context, run.revision)]);
  assert.equal(updates.filter(item => item.status === 'fulfilled').length, 1);
  assert.equal(updates.find(item => item.status === 'rejected').reason.statusCode, 409);
  const fresh = new AutomationRepository({ pool });
  const restarted = new AutomationRuntime(fresh, new PluginRegistry(fresh), { enabled: () => true, authorizeContext: async () => context });
  await restarted.process(run.id); assert.equal((await fresh.get('runs', run.id)).status, 'SUCCEEDED');
  assert.equal((await pool.query('SELECT count(*)::int AS n FROM app.automation_runs')).rows[0].n, 1);
});
