'use strict';
// Offline fixture, not a model evaluation. No provider, Qdrant, SQL or runtime calls.
if (process.env.KNOWLEDGEHUB_TEST_ISOLATED !== '1') throw new Error('Run with --require ./tests/helpers/setup_isolated_data.js');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const definitions = require('../tests/fixtures/lookup_routing_catalog.json');
const tev1 = require('../src/backend/automation/tev1_decision');
const { validateDecision } = require('../src/backend/automation/chat_router');
const { estimateTokens } = require('../src/backend/agent_core/harness/context_budget');
const selected = definitions.find(item => item.routingScope === 'targeted');
const phrase = selected.examples?.[0] || selected.name;
const config = { minProbability: 0.65, minMargin: 0.15 };
const cases = [
  { id: 'execute', question: phrase, purpose: 'execute', route: 'workflow', next: 'Validate permission/version/inputs; runtime asks missing required fields before execution.' },
  { id: 'explain', question: `“${phrase}” hỗ trợ gì?`, purpose: 'explain', route: 'chat', next: 'Recheck authorized published metadata; selected chat model explains, no run mutation or tools.' },
  { id: 'ordinary_chat', question: 'Giải thích khái niệm dữ liệu giúp tôi.', purpose: 'none', route: 'chat', next: 'Continue existing Intelligent Core chat/RAG/tool flow as appropriate.' },
  { id: 'unclear_purpose', question: `“${phrase}”?`, purpose: 'unclear', route: 'unclear', next: 'auto: one selected-chat-model escalation over compact authorized catalog; local_tev1: ask for clarification.' }
];
const samples = cases.map(item => {
  const prepared = tev1.buildTask(item.question, definitions, null);
  const key = prepared.workflows.find(w => w.definition.id === selected.id).key;
  const answers = Object.fromEntries(Object.entries(prepared.task.questions).map(([name, question]) => {
    const keys = Object.keys(question.criteria);
    const choice = name === 'route' ? item.purpose === 'none' ? 'chat' : key
      : name === 'purpose' ? item.purpose
        : name === 'requested_scope' ? item.purpose === 'execute' ? selected.routingScope : 'unclear'
          : name === 'targeted_request' ? item.purpose === 'execute' ? 'yes' : 'no'
            : name === 'aggregate_request' ? 'no'
              : name.startsWith('provided_') ? 'no'
                : name.startsWith('input_') ? 'none' : keys[0];
    return [name, { type: 'choice', choice, probabilities: Object.fromEntries(keys.map(k => [k, k === choice ? 0.98 : 0.02 / (keys.length - 1)])) }];
  }));
  const rawResponse = { answers };
  const converted = tev1.convertAnswers(rawResponse, prepared, item.question, null, config);
  const decision = validateDecision(converted.decision, item.question, definitions, null);
  assert.equal(decision.route, item.route);
  assert.equal(decision.purpose, item.purpose);
  return { scenario: item.id, question: item.question,
    workflowOptions: prepared.workflows.map(w => ({ option: w.key, workflowId: w.definition.id, name: w.definition.name })),
    request: { model: 'tev1:4b', ...prepared.task }, taskTokensEstimate: estimateTokens(prepared.task),
    decisionEvaluations: Object.keys(prepared.task.questions).length,
    simulatedResponse: rawResponse, validatedDecision: decision, nextStepInAuto: item.next };
});
const output = path.resolve(__dirname, '../docs/examples/tev1-routing-simulation.json');
fs.mkdirSync(path.dirname(output), { recursive: true });
fs.writeFileSync(output, JSON.stringify({ simulationOnly: true,
  note: 'Probabilities are invented for demonstration. Tasks and conversion/validation use current production code. w0/w1/w2 are generated by stable workflow-ID sorting, not a hardcoded runtime mapping. No workflow or model was executed.',
  simulatedShortlistSource: 'tests/fixtures/lookup_routing_catalog.json; retrieval is not simulated by this file', thresholds: config, samples }, null, 2) + '\n');
console.log(JSON.stringify({ file: output, validatedScenarios: samples.length }));
