// Human-readable help for every setting exposed by the settings API.
module.exports = {
  PORT: ['Cổng truy cập ứng dụng', 'Cổng HTTP của máy chủ, từ 1 đến 65535. Ví dụ 3000 tương ứng http://localhost:3000; đổi cổng sẽ đổi địa chỉ truy cập.'],
  AI_DEFAULT_TIMEOUT_MS: ['Thời gian chờ AI mặc định', 'Giới hạn chờ mỗi yêu cầu AI, tính bằng mili giây. 30000 = 30 giây; tăng nếu model trả lời chậm.'],
  AI_LOCAL_TIMEOUT_MS: ['Thời gian chờ AI local', 'Giới hạn chờ model chạy nội bộ. 180000 = 3 phút; tăng giúp model chậm có thêm thời gian nhưng người dùng phải chờ lâu hơn.'],
  WEB_SEARCH_ENDPOINT: ['Địa chỉ tìm kiếm web', 'Endpoint được dịch vụ tìm kiếm gọi để lấy kết quả. Cần tương thích với cách ứng dụng đọc kết quả tìm kiếm.'],
  WEB_SEARCH_TIMEOUT_MS: ['Thời gian chờ tìm kiếm', 'Giới hạn thời gian yêu cầu tìm kiếm web. 15000 mili giây = 15 giây.'],
  WEB_SEARCH_MAX_RESULTS: ['Số kết quả tìm kiếm', 'Số kết quả web tối đa được lấy. Tăng để có thêm nguồn tham khảo nhưng nội dung xử lý cũng nhiều hơn.'],
  LOCAL_MODEL_HARNESS_ENABLED: ['Luồng xử lý riêng cho AI local', 'Bật luồng điều phối dành cho model nội bộ để thực hiện gọi công cụ và xử lý kết quả qua nhiều bước.'],
  LOCAL_MODEL_ALLOW_CLOUD_FALLBACK: ['Cho phép chuyển sang AI cloud', 'Cho phép dùng nhà cung cấp cloud khi luồng local cần dự phòng. Có thể gửi ngữ cảnh ra dịch vụ ngoài và phát sinh chi phí.'],
  LOCAL_MODEL_SCHEMA_SELECTOR_ENABLED: ['Cho AI local chọn schema', 'Cho phép model local tham gia chọn cấu trúc bảng liên quan. Có thể tăng số lần gọi model trước khi tạo truy vấn.'],
  LOCAL_MODEL_MAX_ITERATIONS: ['Số vòng xử lý local tối đa', 'Giới hạn vòng suy luận và gọi công cụ cho một yêu cầu local. Tăng cho tác vụ phức tạp, đồng thời tăng thời gian xử lý.'],
  LOCAL_MODEL_MAX_SQL_CALLS: ['Số lần gọi SQL tối đa', 'Giới hạn số lần thực thi công cụ SQL trong một yêu cầu local, giúp kiểm soát tải truy vấn.'],
  LOCAL_MODEL_MAX_REPAIRS: ['Số lần sửa lỗi tối đa', 'Số lần luồng local được thử sửa lỗi. Đặt 0 để không thử sửa; tăng có thể giúp phục hồi nhưng kéo dài thời gian.'],
  LOCAL_MODEL_TOOL_RESULT_CHARS: ['Độ dài kết quả công cụ', 'Ngân sách ký tự cho kết quả công cụ gửi lại model local. Giá trị thấp giảm ngữ cảnh nhưng có thể lược bớt chi tiết.'],
  LOCAL_MODEL_TEMPERATURE: ['Độ ngẫu nhiên của câu trả lời', 'Từ 0 đến 2. Giá trị thấp như 0.1 phù hợp tác vụ SQL cần ổn định; giá trị cao làm câu trả lời đa dạng hơn.'],
  LOCAL_MODEL_NUM_CTX: ['Kích thước ngữ cảnh local', 'Số token ngữ cảnh yêu cầu cho Ollama. Tăng để chứa nhiều thông tin hơn, đồng thời cần thêm bộ nhớ và phải được model hỗ trợ.'],
  LOCAL_MODEL_NUM_PREDICT: ['Giới hạn token đầu ra', 'Số token tối đa model local được sinh. Tăng cho câu trả lời dài; có thể tăng thời gian chạy.'],
  LOCAL_MODEL_KEEP_ALIVE: ['Thời gian giữ model trong bộ nhớ', 'Thời gian Ollama giữ model sau yêu cầu, ví dụ 10m = 10 phút. Giữ lâu giúp lần gọi sau nhanh hơn nhưng chiếm bộ nhớ.'],
  AI_SCHEMA_MAX_TABLES: ['Số bảng trong ngữ cảnh', 'Số bảng tối đa đưa vào ngữ cảnh schema. Tăng hỗ trợ truy vấn nhiều bảng nhưng tiêu tốn thêm token.'],
  AI_SCHEMA_MAX_COLUMNS_PER_TABLE: ['Số cột cho mỗi bảng', 'Giới hạn cột được lấy từ mỗi bảng. Bộ đọc schema dùng tối thiểu 5 cột; tăng khi cần nhiều thuộc tính.'],
  AI_SCHEMA_MAX_CONTEXT_CHARS: ['Độ dài ngữ cảnh schema', 'Ngân sách ký tự mô tả cấu trúc CSDL. Bộ đọc dùng tối thiểu 2000 ký tự; tăng để giữ thêm thông tin bảng và cột.'],
  AI_MEMORY_RECENT_MESSAGES: ['Số tin nhắn gần đây', 'Tham số dự kiến cho số tin nhắn gần nhất trong ngữ cảnh. Chưa thấy mã backend hiện tại đọc biến này; thay đổi có thể chưa có tác dụng.'],
  AI_MEMORY_MAX_MESSAGES: ['Số tin nhắn lưu trong phiên', 'Giới hạn số tin nhắn giữ cho một phiên hội thoại. Tăng để giữ lịch sử dài hơn và dùng thêm dung lượng.'],
  AI_MEMORY_SUMMARY_CHARS: ['Độ dài tóm tắt hội thoại', 'Ngân sách ký tự dự kiến cho tóm tắt. Chưa thấy mã backend hiện tại đọc biến này; thay đổi có thể chưa có tác dụng.'],
  AI_MEMORY_MAX_SESSIONS: ['Số phiên hội thoại tối đa', 'Giới hạn số phiên được bộ nhớ hội thoại lưu giữ. Tăng khi cần phục vụ nhiều phiên đồng thời.'],
  QDRANT_URL: ['Địa chỉ Qdrant', 'URL dịch vụ vector, ví dụ http://127.0.0.1:6333. Đây là nơi lưu chỉ mục để tìm schema và tài liệu liên quan.'],
  QDRANT_EXE: ['Chương trình Qdrant', 'Đường dẫn file chạy Qdrant trên máy chủ Windows. Sau khi thay đổi, lưu và khởi động lại để supervisor sử dụng đường dẫn mới.'],
  QDRANT_COLLECTION: ['Collection cấu trúc CSDL', 'Tên tập vector dành cho schema. Đổi tên sẽ trỏ sang tập dữ liệu khác; cần có chỉ mục tương ứng.'],
  QDRANT_VECTOR_SIZE: ['Số chiều vector schema', 'Phải khớp kích thước vector của model và collection schema. Không đổi riêng giá trị này nếu chưa chuẩn bị collection phù hợp.'],
  LIBRARY_MAX_FILE_MB: ['Dung lượng tài liệu tối đa', 'Giới hạn kích thước mỗi tài liệu tải lên, tính bằng MB. Tăng cho file lớn hơn nhưng cần thêm tài nguyên xử lý.'],
  QDRANT_DOCUMENT_COLLECTION: ['Collection tài liệu', 'Tên tập vector của thư viện tri thức. Khi chuyển model embedding, nên dùng collection tương thích và lập chỉ mục lại.'],
  QDRANT_DOCUMENT_VECTOR_SIZE: ['Số chiều vector tài liệu', 'Phải khớp đầu ra model embedding tài liệu. Ví dụ BGE-M3 thường dùng 1024 chiều.'],
  AI_DOCUMENT_CONTEXT_CHARS: ['Độ dài ngữ cảnh tài liệu', 'Ngân sách ký tự tài liệu gửi cho AI để trả lời. Tăng để có thêm trích đoạn nhưng sẽ dùng nhiều ngữ cảnh hơn.'],
  AI_DOCUMENT_MIN_SCORE: ['Ngưỡng liên quan tài liệu', 'Ngưỡng điểm từ 0 đến 1 để chọn tài liệu. Tăng giúp lọc chặt hơn nhưng có thể bỏ sót kết quả hữu ích.'],
  EMBEDDING_PROVIDER: ['Dịch vụ tạo embedding', 'ollama: dùng Ollama nội bộ; openai: endpoint tương thích OpenAI. Dịch vụ chuyển văn bản thành vector để tìm kiếm.'],
  EMBEDDING_BASE_URL: ['Địa chỉ dịch vụ embedding', 'URL máy chủ cung cấp model embedding, ví dụ http://127.0.0.1:11434 cho Ollama.'],
  EMBEDDING_MODEL: ['Model embedding', 'Tên model chuyển văn bản thành vector, ví dụ bge-m3. Đổi model có thể yêu cầu đổi số chiều và lập chỉ mục tài liệu lại.'],
  EMBEDDING_FALLBACK_MODE: ['Xử lý khi embedding lỗi', 'error: báo lỗi và dừng. deterministic: dùng vector dự phòng, không đảm bảo chất lượng tìm kiếm ngữ nghĩa.'],
  RETRIEVAL_CANDIDATE_LIMIT: ['Số ứng viên tìm kiếm', 'Số kết quả ứng viên cho bước truy xuất. Tăng để xét nhiều đoạn hơn trước khi chọn nội dung gửi AI.'],
  RRF_K: ['Hệ số gộp thứ hạng', 'Hệ số Reciprocal Rank Fusion khi kết hợp các nguồn tìm kiếm. Giá trị lớn giảm chênh lệch trọng số giữa các vị trí đứng đầu.'],
  RERANKER_ENABLED: ['Xếp hạng lại kết quả', 'Bật model reranker để đánh giá lại độ liên quan của kết quả. Cần dịch vụ reranker hoạt động và có thể tăng độ trễ.'],
  RERANKER_BASE_URL: ['Địa chỉ reranker', 'URL dịch vụ xếp hạng lại kết quả, được dùng khi bật reranker.'],
  RERANKER_MODEL: ['Model reranker', 'Tên model đánh giá độ phù hợp giữa câu hỏi và đoạn tài liệu. Phải được dịch vụ reranker hỗ trợ.'],
  GRAPHRAG_ENABLED: ['Tìm kiếm theo quan hệ', 'Bật khả năng truy xuất theo quan hệ khi câu hỏi phù hợp, bổ sung cho tìm kiếm văn bản và vector.'],
  KNOWLEDGE_REINDEX_ON_START: ['Lập chỉ mục lại khi khởi động', 'Bật để xây dựng lại chỉ mục tri thức ở lần khởi động. Có thể mất nhiều thời gian; tắt sau khi hoàn tất.'],
  AI_MAX_TOOL_ITERATIONS: ['Số vòng gọi công cụ AI', 'Giới hạn vòng gọi công cụ của luồng AI chính. Tăng cho tác vụ nhiều bước nhưng cần thêm thời gian và token.'],
  LOCAL_AI_MODEL: ['Model local khi khởi chạy', 'Tên model được script start-local.ps1 sử dụng, ví dụ qwen3.5:9b. Cấu hình provider trong ứng dụng được quản lý riêng.']
};
